/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package reservationsystem;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.DefaultCellEditor;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

public class dashboardFrame extends javax.swing.JFrame {
    private static final String DB_URL = "jdbc:mysql://localhost:3306/studentreservation";
    private static final String USER = "root";
    private static final String PASS = "";
    EquipmentReservation equip = new EquipmentReservation();
    Appointment appoint = new Appointment();
    private String studentNumber;
    private User user;
    long professorID[];
    long officeID[];
    int index=0;
    int index2=0;
    public dashboardFrame(User user) {
        this.user = user;
        initComponents();
        setDefaultCloseOperation(Login.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        
        professorID = new long[100];
        officeID = new long[100];
        try{
            Connection connection = DriverManager.getConnection(DB_URL, USER, PASS);
            String profquery = "Select professorID, professorName From professor";
            PreparedStatement pst = connection.prepareStatement(profquery);
            ResultSet rst = pst.executeQuery();
            while(rst.next()){
                professorID[index] = rst.getLong(1);
                index++;
                professorComboBox.addItem(rst.getString(2));
            }
            rst.close();
        }catch(Exception ex){
            ex.printStackTrace();
        }
        try{
            Connection connection = DriverManager.getConnection(DB_URL, USER, PASS);
            String officequery = "SELECT officeID, room FROM office";
            PreparedStatement pst = connection.prepareStatement(officequery);
            ResultSet rst = pst.executeQuery();
            while(rst.next()){
                officeID[index2] = rst.getLong(1);
                index2++;
                officeComboBox.addItem(rst.getString(2));
            }
            rst.close();
            
        }catch(Exception ex){
            ex.printStackTrace();
        }
        //User Profile
            fnameLabel.setText("Hello! " + user.getName() + " " + user.getlastName());
            yearSectionLabel.setText(user.getYearSection());
            studentNumberLabel.setText("Student number : " +user.getStudentNumber());
            emailLabel.setText(user.getemail());
            programLabel.setText(user.getprogram());
            birthDateLabel.setText(user.getbirthDate());
            contactNumberLabel.setText(user.getcontactNumber());
        //Appointment
            fnameLabel1.setText("Name: " + user.getName() + " " + user.getlastName());
            studNumApptLabel.setText("Student Number: " + user.getStudentNumber());
        //Table History
            TableColumnModel tcm1 = resHistoryTable.getColumnModel();
            tcm1.removeColumn( tcm1.getColumn(0) );
            TableColumnModel tcm2 = apptResHistory.getColumnModel();
            tcm2.removeColumn( tcm2.getColumn(0) );
        
            equip.getReservationHistory(user.getId(),resHistoryTable);
            equip.getAllReservation(projectorTable,screenTable,speakerTable,micTable);
            appoint.getAppointmentHistory(user.getId(),apptResHistory);
            
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel10 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        userButton = new javax.swing.JButton();
        apptButton = new javax.swing.JButton();
        equipButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        titleBar = new javax.swing.JLabel();
        parentPanel = new javax.swing.JPanel();
        userPanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        fnameLabel = new javax.swing.JLabel();
        studentNumberLabel = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        searchTextField1 = new javax.swing.JTextField();
        yearSectionLabel = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        apptResHistory = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        resHistoryTable = new javax.swing.JTable();
        studentNumberLabel4 = new javax.swing.JLabel();
        studentNumberLabel5 = new javax.swing.JLabel();
        studentNumberLabel3 = new javax.swing.JLabel();
        studentNumberLabel2 = new javax.swing.JLabel();
        studentNumberLabel1 = new javax.swing.JLabel();
        contactNumberLabel = new javax.swing.JLabel();
        birthDateLabel = new javax.swing.JLabel();
        programLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        apptPanel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        concernTextArea = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        officeComboBox = new javax.swing.JComboBox<>();
        timeComboBox = new javax.swing.JComboBox<>();
        fnameLabel3 = new javax.swing.JLabel();
        apptSubmitButton = new javax.swing.JButton();
        apptDateChooser = new com.toedter.calendar.JDateChooser();
        studNumApptLabel = new javax.swing.JLabel();
        fnameLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        fnameLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        fnameLabel4 = new javax.swing.JLabel();
        equipPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        equipCheckBox1 = new javax.swing.JCheckBox();
        equipCheckBox3 = new javax.swing.JCheckBox();
        equipCheckBox4 = new javax.swing.JCheckBox();
        equipCheckBox2 = new javax.swing.JCheckBox();
        professorComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        equipSubmitButton = new javax.swing.JButton();
        dateChooser = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        timeComboBox2 = new javax.swing.JComboBox<>();
        timeComboBox1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        purposeTextArea = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        checkButton = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        projectorTable = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        screenTable = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        speakerTable = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        micTable = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        refreshButton1 = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(846, 604));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(125, 13, 9));

        userButton.setBackground(new java.awt.Color(125, 13, 9));
        userButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userButton.setForeground(new java.awt.Color(255, 255, 255));
        userButton.setText("User");
        userButton.setBorder(null);
        userButton.setBorderPainted(false);
        userButton.setDefaultCapable(false);
        userButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userButtonActionPerformed(evt);
            }
        });

        apptButton.setBackground(new java.awt.Color(125, 13, 9));
        apptButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        apptButton.setForeground(new java.awt.Color(255, 255, 255));
        apptButton.setText("Student Appointment");
        apptButton.setBorder(null);
        apptButton.setBorderPainted(false);
        apptButton.setDefaultCapable(false);
        apptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apptButtonActionPerformed(evt);
            }
        });

        equipButton.setBackground(new java.awt.Color(125, 13, 9));
        equipButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        equipButton.setForeground(new java.awt.Color(255, 255, 255));
        equipButton.setText("Equipment Reservation");
        equipButton.setBorder(null);
        equipButton.setBorderPainted(false);
        equipButton.setDefaultCapable(false);
        equipButton.setPreferredSize(new java.awt.Dimension(160, 20));
        equipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipButtonActionPerformed(evt);
            }
        });

        logoutButton.setBackground(new java.awt.Color(125, 13, 9));
        logoutButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Logout");
        logoutButton.setBorder(null);
        logoutButton.setBorderPainted(false);
        logoutButton.setDefaultCapable(false);
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(apptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(equipButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(userButton, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addGap(33, 33, 33))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(userButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(apptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(equipButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        jPanel3.setBackground(new java.awt.Color(211, 144, 100));

        titleBar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titleBar.setText("PUP PARAÑAQUE APPOINTMENT AND RESERVATION SYSTEM");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleBar, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleBar, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        parentPanel.setLayout(new java.awt.CardLayout());

        userPanel.setBackground(new java.awt.Color(153, 153, 255));

        jPanel6.setBackground(new java.awt.Color(0, 0, 51));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));

        fnameLabel.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        fnameLabel.setForeground(new java.awt.Color(255, 255, 255));
        fnameLabel.setText("placeholder username");

        studentNumberLabel.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        studentNumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        studentNumberLabel.setText("placeholder student Number");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(328, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(studentNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(fnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel9.setBackground(new java.awt.Color(153, 153, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancelButton.setBackground(new java.awt.Color(255, 0, 0));
        cancelButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancel Reservation");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel9.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 452, 140, 30));

        searchTextField1.setForeground(new java.awt.Color(153, 153, 153));
        searchTextField1.setText("search");
        searchTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchTextField1FocusLost(evt);
            }
        });
        searchTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextField1ActionPerformed(evt);
            }
        });
        jPanel9.add(searchTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 452, 200, 30));

        yearSectionLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        yearSectionLabel.setForeground(new java.awt.Color(0, 0, 0));
        yearSectionLabel.setText("placeholder year-section");
        jPanel9.add(yearSectionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 22, 160, 34));

        refreshButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        refreshButton.setText("refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        jPanel9.add(refreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 452, 80, 30));

        apptResHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Id","Date", "Time", "Office"
            }
        ){
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        });
        apptResHistory.setSelectionBackground(new java.awt.Color(0, 204, 0));
        apptResHistory.getTableHeader().setReorderingAllowed(false);
        apptResHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apptResHistoryMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(apptResHistory);

        jTabbedPane1.addTab("Appointment History", jScrollPane3);

        resHistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "id","Date", "Time In","Time Out", "Equipment"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        });
        resHistoryTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        resHistoryTable.setSelectionBackground(new java.awt.Color(0, 204, 0));
        resHistoryTable.getTableHeader().setReorderingAllowed(false);
        resHistoryTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resHistoryTableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(resHistoryTable);

        jTabbedPane1.addTab("Reservation History", jScrollPane5);

        jPanel9.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 152, 590, 300));

        studentNumberLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        studentNumberLabel4.setForeground(new java.awt.Color(0, 0, 0));
        studentNumberLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        studentNumberLabel4.setText("Birth date :");
        jPanel9.add(studentNumberLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 22, 100, 34));

        studentNumberLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        studentNumberLabel5.setForeground(new java.awt.Color(0, 0, 0));
        studentNumberLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        studentNumberLabel5.setText("Contact Number :");
        jPanel9.add(studentNumberLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 112, 130, 34));

        studentNumberLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        studentNumberLabel3.setForeground(new java.awt.Color(0, 0, 0));
        studentNumberLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        studentNumberLabel3.setText("Course :");
        jPanel9.add(studentNumberLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 82, 100, 34));

        studentNumberLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        studentNumberLabel2.setForeground(new java.awt.Color(0, 0, 0));
        studentNumberLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        studentNumberLabel2.setText("Email :");
        jPanel9.add(studentNumberLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 52, 100, 34));

        studentNumberLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        studentNumberLabel1.setForeground(new java.awt.Color(0, 0, 0));
        studentNumberLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        studentNumberLabel1.setText("Year-Section :");
        jPanel9.add(studentNumberLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 22, 100, 34));

        contactNumberLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        contactNumberLabel.setForeground(new java.awt.Color(0, 0, 0));
        contactNumberLabel.setText("placeholder contact number");
        jPanel9.add(contactNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 112, 190, 34));

        birthDateLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        birthDateLabel.setForeground(new java.awt.Color(0, 0, 0));
        birthDateLabel.setText("placeholder birthdate");
        jPanel9.add(birthDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 22, 140, 34));

        programLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        programLabel.setForeground(new java.awt.Color(0, 0, 0));
        programLabel.setText("placeholder program");
        jPanel9.add(programLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 82, 340, 31));

        emailLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(0, 0, 0));
        emailLabel.setText("placeholder email");
        jPanel9.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 52, 190, 34));

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
        );

        parentPanel.add(userPanel, "card2");

        apptPanel.setBackground(new java.awt.Color(51, 51, 51));

        jPanel7.setBackground(new java.awt.Color(204, 153, 0));

        jLabel13.setBackground(new java.awt.Color(204, 153, 0));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Student Appointment");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 153));

        concernTextArea.setColumns(20);
        concernTextArea.setForeground(new java.awt.Color(153, 153, 153));
        concernTextArea.setRows(5);
        concernTextArea.setText("provide a brief description to your concern...");
        concernTextArea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                concernTextAreaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                concernTextAreaFocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(concernTextArea);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        )
    );
    jScrollPane4.setViewportView(jTable1);

    timeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10:00 AM", "11:00 AM", "1:00 PM", "2:00 PM", "3:00 PM", "4:00 PM" }));

    fnameLabel3.setBackground(new java.awt.Color(0, 0, 0));
    fnameLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
    fnameLabel3.setForeground(new java.awt.Color(0, 0, 0));
    fnameLabel3.setText("Office Appointment");

    apptSubmitButton.setBackground(new java.awt.Color(0, 102, 0));
    apptSubmitButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    apptSubmitButton.setForeground(new java.awt.Color(255, 255, 255));
    apptSubmitButton.setText("Submit");
    apptSubmitButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            apptSubmitButtonActionPerformed(evt);
        }
    });

    studNumApptLabel.setBackground(new java.awt.Color(0, 0, 0));
    studNumApptLabel.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
    studNumApptLabel.setForeground(new java.awt.Color(0, 0, 0));
    studNumApptLabel.setText("placeholder student number");

    fnameLabel1.setBackground(new java.awt.Color(0, 0, 0));
    fnameLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
    fnameLabel1.setForeground(new java.awt.Color(0, 0, 0));
    fnameLabel1.setText("placeholder username");

    jButton3.setBackground(new java.awt.Color(51, 51, 0));
    jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jButton3.setForeground(new java.awt.Color(255, 255, 255));
    jButton3.setText("check schedule");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
        }
    });

    fnameLabel5.setBackground(new java.awt.Color(0, 0, 0));
    fnameLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
    fnameLabel5.setForeground(new java.awt.Color(0, 0, 0));
    fnameLabel5.setText("Time");

    jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

    fnameLabel4.setBackground(new java.awt.Color(0, 0, 0));
    fnameLabel4.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
    fnameLabel4.setForeground(new java.awt.Color(0, 0, 0));
    fnameLabel4.setText("Appointment Date");

    javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
    jPanel8.setLayout(jPanel8Layout);
    jPanel8Layout.setHorizontalGroup(
        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel8Layout.createSequentialGroup()
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(fnameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(5, 5, 5)
                    .addComponent(studNumApptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fnameLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addGap(150, 150, 150)
                            .addComponent(officeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addGap(150, 150, 150)
                            .addComponent(apptDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(fnameLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addComponent(fnameLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(timeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(150, 150, 150)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(69, 69, 69)
                    .addComponent(apptSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(12, Short.MAX_VALUE))
    );
    jPanel8Layout.setVerticalGroup(
        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel8Layout.createSequentialGroup()
            .addGap(10, 10, 10)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(fnameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(studNumApptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(6, 6, 6)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(fnameLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(officeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(6, 6, 6)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(apptDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(fnameLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(fnameLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(timeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(5, 5, 5)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, 0)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(apptSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(30, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout apptPanelLayout = new javax.swing.GroupLayout(apptPanel);
    apptPanel.setLayout(apptPanelLayout);
    apptPanelLayout.setHorizontalGroup(
        apptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    apptPanelLayout.setVerticalGroup(
        apptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(apptPanelLayout.createSequentialGroup()
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    parentPanel.add(apptPanel, "card3");

    equipPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jPanel4.setBackground(new java.awt.Color(51, 0, 51));

    jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Equipment Reservation");

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addGap(0, 0, 0)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    equipPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 608, -1));

    jPanel5.setBackground(new java.awt.Color(255, 204, 255));
    jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(0, 0, 0));
    jLabel2.setText("Pick an item to make a reservation");
    jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 30));

    equipCheckBox1.setForeground(new java.awt.Color(0, 0, 0));
    equipCheckBox1.setText("Projector");
    equipCheckBox1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            equipCheckBox1ActionPerformed(evt);
        }
    });
    jPanel5.add(equipCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 85, -1));

    equipCheckBox3.setForeground(new java.awt.Color(0, 0, 0));
    equipCheckBox3.setText("Speaker");
    equipCheckBox3.setToolTipText("");
    jPanel5.add(equipCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 85, -1));

    equipCheckBox4.setForeground(new java.awt.Color(0, 0, 0));
    equipCheckBox4.setText("Microphone");
    jPanel5.add(equipCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 99, -1));

    equipCheckBox2.setForeground(new java.awt.Color(0, 0, 0));
    equipCheckBox2.setText("Projection Screen");
    jPanel5.add(equipCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

    professorComboBox.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            professorComboBoxActionPerformed(evt);
        }
    });
    jPanel5.add(professorComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 220, 31));

    jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(0, 0, 0));
    jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel4.setText("Professor:");
    jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 70, 30));

    equipSubmitButton.setBackground(new java.awt.Color(0, 102, 0));
    equipSubmitButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    equipSubmitButton.setForeground(new java.awt.Color(255, 255, 255));
    equipSubmitButton.setText("Submit");
    equipSubmitButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            equipSubmitButtonActionPerformed(evt);
        }
    });
    jPanel5.add(equipSubmitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 130, 33));
    jPanel5.add(dateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 220, 31));

    jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reservationsystem/EB-2165W-02.png"))); // NOI18N
    jLabel6.setText("Item 1");
    jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 93, 82));

    jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reservationsystem/images-1-removebg-preview.png"))); // NOI18N
    jLabel7.setText("jLabel7");
    jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 73, -1));

    jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reservationsystem/isb380b-front-handle-up-2-copy-r.png"))); // NOI18N
    jLabel8.setText("jLabel8");
    jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 82, -1));

    jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reservationsystem/resize-1-removebg-preview (1).png"))); // NOI18N
    jLabel9.setText("Item2");
    jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 94, 80));

    timeComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Time Out", "8:00 AM", "9:00 AM", "10:00 AM", "11:00 AM", "12:00 AM", "1:00 PM", "2:00 PM", "3:00 PM", "4:00 PM", "5:00 PM", "6:00 PM", "7:00 PM", "8:00 PM", "9:00 PM" }));
    jPanel5.add(timeComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 110, 30));

    timeComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Time In", "7:00 AM", "8:00 AM", "9:00 AM", "10:00 AM", "11:00 AM", "12:00 AM", "1:00 PM", "2:00 PM", "3:00 PM", "4:00 PM", "5:00 PM", "6:00 PM", "7:00 PM" }));
    jPanel5.add(timeComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 100, 30));

    jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel10.setForeground(new java.awt.Color(0, 0, 0));
    jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel10.setText("Purpose:");
    jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 60, -1));

    purposeTextArea.setColumns(20);
    purposeTextArea.setForeground(new java.awt.Color(153, 153, 153));
    purposeTextArea.setRows(5);
    purposeTextArea.setText("Provide a brief description...");
    purposeTextArea.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            purposeTextAreaFocusGained(evt);
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            purposeTextAreaFocusLost(evt);
        }
    });
    jPanel5.add(purposeTextArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 290, 140));

    jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel11.setForeground(new java.awt.Color(0, 0, 0));
    jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel11.setText("Time:");
    jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 70, 30));

    checkButton.setBackground(new java.awt.Color(51, 51, 0));
    checkButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    checkButton.setForeground(new java.awt.Color(255, 255, 255));
    checkButton.setText("check availability");
    checkButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            checkButtonActionPerformed(evt);
        }
    });
    jPanel5.add(checkButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 130, 30));

    jScrollPane1.setEnabled(false);

    projectorTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
        },
        new String [] {
            "Date","Time In","Time Out"
        }
    ){
        public boolean isCellEditable (int rowIndex, int columnIndex){return false;}
    });
    projectorTable.getTableHeader().setReorderingAllowed(false);
    jScrollPane1.setViewportView(projectorTable);

    jTabbedPane2.addTab("Item 1", jScrollPane1);

    screenTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
        },
        new String [] {
            "Date","Time In","Time Out"
        }
    ));
    screenTable.setEnabled(false);
    screenTable.getTableHeader().setReorderingAllowed(false);
    jScrollPane6.setViewportView(screenTable);

    jTabbedPane2.addTab("Item 2", jScrollPane6);

    speakerTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
        },
        new String [] {
            "Date","Time In","Time Out"
        }
    ));
    speakerTable.setEnabled(false);
    speakerTable.getTableHeader().setReorderingAllowed(false);
    jScrollPane7.setViewportView(speakerTable);

    jTabbedPane2.addTab("Item 3", jScrollPane7);

    micTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "Date","Time In","Time Out"
        }
    ));
    micTable.setEnabled(false);
    micTable.getTableHeader().setReorderingAllowed(false);
    jScrollPane8.setViewportView(micTable);

    jTabbedPane2.addTab("Item 4", jScrollPane8);

    jPanel5.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 280, 280));

    jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel12.setForeground(new java.awt.Color(0, 0, 0));
    jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel12.setText("Date:");
    jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 70, 30));

    refreshButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    refreshButton1.setText("refresh");
    refreshButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            refreshButton1ActionPerformed(evt);
        }
    });
    jPanel5.add(refreshButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 80, 30));

    equipPanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 66, 608, 509));

    parentPanel.add(equipPanel, "card4");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, 0)
            .addComponent(parentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, 0)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(parentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?", "Confirm Logout", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            // Close current frame
            this.dispose();

            // Open login frame
            Login loginFrame = new Login();
            loginFrame.setVisible(true);
        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void equipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipButtonActionPerformed
        parentPanel.removeAll();
        parentPanel.add(equipPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_equipButtonActionPerformed

    private void apptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apptButtonActionPerformed
        parentPanel.removeAll();
        parentPanel.add(apptPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_apptButtonActionPerformed

    private void userButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userButtonActionPerformed
        parentPanel.removeAll();
        parentPanel.add(userPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_userButtonActionPerformed

    private void equipCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equipCheckBox1ActionPerformed

    private void professorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_professorComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_professorComboBoxActionPerformed
        
    private void equipSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipSubmitButtonActionPerformed
        int gettimeIN = timeComboBox1.getSelectedIndex();
        int gettimeOUT = timeComboBox2.getSelectedIndex();
        String[] listTimeIN = {"","7:00:00", "8:00:00", "9:00:00", "10:00:00","11:00:00", "12:00:00", "13:00:00", "14:00:00", "15:00:00", "16:00:00","17:00:00","18:00:00","19:00:00"};
        String[] lsitTimeOUT = {"", "8:00:00", "9:00:00", "10:00:00","11:00:00", "12:00:00", "13:00:00", "14:00:00", "15:00:00", "16:00:00","17:00:00","18:00:00","19:00:00","20:00:00","21:00:00"};
        String timeIN = listTimeIN[gettimeIN];
        String timeOUT = lsitTimeOUT[gettimeOUT];
        boolean equipment1 = equipCheckBox1.isSelected();
        boolean equipment2 = equipCheckBox2.isSelected();
        boolean equipment3 = equipCheckBox3.isSelected();
        boolean equipment4 = equipCheckBox4.isSelected();
        String purpose = purposeTextArea.getText();

        if (!equipment1 && !equipment2 && !equipment3 && !equipment4){
            JOptionPane.showMessageDialog(rootPane, "Please select an equipment");
            return;
        }
        else if (dateChooser.getDate() == null){
            JOptionPane.showMessageDialog(rootPane, "Please select a date for your reservation");
            return;
        }
        else if(gettimeIN == 0 || gettimeOUT == 0){
            JOptionPane.showMessageDialog(rootPane, "Please select a time for your reservation");
            return;
        }
        else if(purpose.equals("Provide a brief description...") || purpose.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Provide a short description to your reservation");
            return;
        }
        else{
            JOptionPane.showMessageDialog(this, "Equipment reserved successfully!");
            
            resHistoryTable.setModel(new DefaultTableModel(null,new Object[]{"id","Date", "Time In","Time Out", "Equipment"}){public boolean isCellEditable(int rowIndex,int oolumnIndex){return false;}});
            
            projectorTable.setModel(new DefaultTableModel(null,new Object[]{"Date","Time In","Time Out"}){public boolean isCellEditable(int rowIndex,int oolumnIndex){return false;}});
            screenTable.setModel(new DefaultTableModel(null,new Object[]{"Date","Time In","Time Out"}){public boolean isCellEditable(int rowIndex,int oolumnIndex){return false;}});
            speakerTable.setModel(new DefaultTableModel(null,new Object[]{"Date","Time In","Time Out"}){public boolean isCellEditable(int rowIndex,int oolumnIndex){return false;}});
            micTable.setModel(new DefaultTableModel(null,new Object[]{"Date","Time In","Time Out"}){public boolean isCellEditable(int rowIndex,int oolumnIndex){return false;}});
        }

        int studentID = user.getId();

        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String date = dateFormat.format(dateChooser.getDate());

        List<Integer> equipmentIDs = new ArrayList<>();
        if (equipCheckBox1.isSelected()) equipmentIDs.add(1); 
        if (equipCheckBox2.isSelected()) equipmentIDs.add(2); 
        if (equipCheckBox3.isSelected()) equipmentIDs.add(3); 
        if (equipCheckBox4.isSelected()) equipmentIDs.add(4); 
        try {
            Connection connection = DriverManager.getConnection(DB_URL, USER, PASS);
            String dateTimeSQL = "INSERT INTO dateandtime(date,timeIN,timeOUT) VALUES (?,?,?)";
            PreparedStatement dateTimeStatement = connection.prepareStatement(dateTimeSQL, Statement.RETURN_GENERATED_KEYS);
            dateTimeStatement.setString(1, date);
            dateTimeStatement.setString(2, timeIN);
            dateTimeStatement.setString(3, timeOUT);
            
            int dateTimeRowsInserted = dateTimeStatement.executeUpdate();
            long dateTimeID = 0;
            if (dateTimeRowsInserted > 0) {
                ResultSet generatedKeys = dateTimeStatement.getGeneratedKeys();
                if (generatedKeys.next()) {
                    dateTimeID = generatedKeys.getLong(1);
                }
            }
            
            String sql = "INSERT INTO equipmentreservation (studentID, professorID, dateTimeID, equipmentID, purpose) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement statement = connection.prepareStatement(sql);

            for (int equipmentID : equipmentIDs) {
                statement.setInt(1, studentID);
                statement.setLong(2, professorID[professorComboBox.getSelectedIndex()]);
                statement.setLong(3, dateTimeID);
                statement.setInt(4, equipmentID);
                statement.setString(5, purpose);

                statement.executeUpdate();
                
            }
            
            //clears the form
            professorComboBox.setSelectedIndex(0);
            equipCheckBox1.setSelected(false);
            equipCheckBox2.setSelected(false);
            equipCheckBox3.setSelected(false);
            equipCheckBox4.setSelected(false);
            dateChooser.setCalendar(null);
            timeComboBox1.setSelectedIndex(0);
            timeComboBox2.setSelectedIndex(0);
            purposeTextArea.setText("");
           
            // Close the statement and connection
            dateTimeStatement.close();
            statement.close();
            connection.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        TableColumnModel tcm = resHistoryTable.getColumnModel();
        tcm.removeColumn( tcm.getColumn(0) );
        equip.getReservationHistory(user.getId(),resHistoryTable);
        equip.getAllReservation(projectorTable,screenTable,speakerTable,micTable);
        
        
    }//GEN-LAST:event_equipSubmitButtonActionPerformed

    private void resHistoryTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resHistoryTableMouseClicked
        // TODO add your handling code here:
        DefaultCellEditor editor = (DefaultCellEditor) resHistoryTable.getDefaultEditor(Object.class);
        editor.setClickCountToStart(1);
    }//GEN-LAST:event_resHistoryTableMouseClicked

    private void apptSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apptSubmitButtonActionPerformed
        int getTimeIN=timeComboBox.getSelectedIndex();
        String[] listTime = {"10:00:00","11:00:00","13:00:00","14:00:00","15:00:00","16:00:00"};
        String timeIN = listTime[getTimeIN];
        int studentID = user.getId();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String date = dateFormat.format(apptDateChooser.getDate());
        String concern = concernTextArea.getText();
        try {
            Connection connection = DriverManager.getConnection(DB_URL, USER, PASS);
            String apptdatetimeSQL = "INSERT INTO dateandtime(date,timeIN) VALUES (?,?)";
            PreparedStatement dateTimeStatement = connection.prepareStatement(apptdatetimeSQL, Statement.RETURN_GENERATED_KEYS);
            dateTimeStatement.setString(1, date);
            dateTimeStatement.setString(2, timeIN);
            
            int dateTimeRowsInserted = dateTimeStatement.executeUpdate();
            long dateTimeID = 0;
            if (dateTimeRowsInserted > 0) {
                ResultSet generatedKeys = dateTimeStatement.getGeneratedKeys();
                if (generatedKeys.next()) {
                    dateTimeID = generatedKeys.getLong(1);
                }
            }
            
            String sql = "INSERT INTO studentappointment (studentID, officeID, dateTimeID, concern) VALUES (?, ?, ?, ?)";
            PreparedStatement statement = connection.prepareStatement(sql);

                statement.setInt(1, studentID);
                statement.setLong(2, officeID[officeComboBox.getSelectedIndex()]);
                statement.setLong(3, dateTimeID);
                statement.setString(4, concern);
            int rowsInserted = statement.executeUpdate();   
            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(this, "Your appointment has been booked.");
                // Clears the Registration form
                concernTextArea.setText("provide a brief description to your concern...");
                officeComboBox.setSelectedIndex(0);
                timeComboBox.setSelectedIndex(0);
                apptDateChooser.setCalendar(null);
            }
            
            dateTimeStatement.close();
            statement.close();
            connection.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
            
        apptResHistory.setModel(new DefaultTableModel(null,new Object[]{"id","Date", "Time", "Office"}){public boolean isCellEditable(int rowIndex,int oolumnIndex){return false;}});
        TableColumnModel tcm2 = apptResHistory.getColumnModel();
        tcm2.removeColumn( tcm2.getColumn(0) );
        appoint.getAppointmentHistory(user.getId(),apptResHistory);
    }//GEN-LAST:event_apptSubmitButtonActionPerformed

    private void searchTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextField1ActionPerformed
        /*String search = searchTextField1.getText();
        try{
            Connection connection = DriverManager.getConnection(DB_URL, USER, PASS);
            String searchSQL = "SELECT ap.studentID, dt.date, dt.timeIN, o.room, ap.concern "
                    + "FROM studentappointment ap " +
                     "JOIN dateandtime dt ON ap.datetimeID = dt.dateTimeID " +
                     "JOIN office o ON ap.officeID = o.officeID "
                + "WHERE ap.studentid = ? and o.office = ? or dt.date = ?"
                    + "ORDER BY dt.date ASC";
            PreparedStatement statement = connection.prepareStatement(searchSQL);
            statement.setInt(1, studentID);
            statement.setString(2, office);
            statement.setString(3, date);
        } catch (SQLException ex){
            ex.printStackTrace();
        }*/
        
    }//GEN-LAST:event_searchTextField1ActionPerformed

    private void searchTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTextField1FocusGained
        // placeholder
        if (searchTextField1.getText().equals("search")){
            searchTextField1.setText("");
            searchTextField1.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_searchTextField1FocusGained

    private void searchTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTextField1FocusLost
        // placeholder
        if (searchTextField1.getText().equals("")){
            searchTextField1.setText("search");
            searchTextField1.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_searchTextField1FocusLost

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void concernTextAreaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_concernTextAreaFocusGained
        if (concernTextArea.getText().equals("provide a brief description to your concern...")){
            concernTextArea.setText("");
            concernTextArea.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_concernTextAreaFocusGained

    private void concernTextAreaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_concernTextAreaFocusLost
        if (concernTextArea.getText().equals("")){
            concernTextArea.setText("provide a brief description to your concern...");
            concernTextArea.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_concernTextAreaFocusLost

    private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkButtonActionPerformed
        DefaultTableModel model1 = new DefaultTableModel(null, new Object[]{"Date", "Time In", "Time Out"});
        DefaultTableModel model2 = new DefaultTableModel(null, new Object[]{"Date", "Time In", "Time Out"});
        DefaultTableModel model3 = new DefaultTableModel(null, new Object[]{"Date", "Time In", "Time Out"}); 
        DefaultTableModel model4 = new DefaultTableModel(null, new Object[]{"Date", "Time In", "Time Out"}); 
        if (dateChooser.getDate() == null){
            JOptionPane.showMessageDialog(rootPane, "Please select a date to view the table");
            return;
        }
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String date = dateFormat.format(dateChooser.getDate());
            

        String projectorSQL = "SELECT dt.date, dt.timeIN, dt.timeOUT, er.equipmentID "
                + "FROM equipmentreservation er "
                + "JOIN dateandtime dt ON er.datetimeID = dt.dateTimeID "
                + "JOIN equipment e ON er.equipmentID = e.equipmentID "
                + "WHERE dt.date = ? and er.equipmentID = 1 ORDER BY dt.date ASC, dt.timeIN ASC";
        String screenSQL = "SELECT dt.date, dt.timeIN, dt.timeOUT, er.equipmentID "
                + "FROM equipmentreservation er "
                + "JOIN dateandtime dt ON er.datetimeID = dt.dateTimeID "
                + "JOIN equipment e ON er.equipmentID = e.equipmentID "
                + "WHERE dt.date = ? and er.equipmentID = 2 ORDER BY dt.date ASC, dt.timeIN ASC";
        String speakerSQL = "SELECT dt.date, dt.timeIN, dt.timeOUT, er.equipmentID "
                + "FROM equipmentreservation er "
                + "JOIN dateandtime dt ON er.datetimeID = dt.dateTimeID "
                + "JOIN equipment e ON er.equipmentID = e.equipmentID "
                + "WHERE dt.date = ? and er.equipmentID = 3 ORDER BY dt.date ASC, dt.timeIN ASC";
        String micSQL = "SELECT dt.date, dt.timeIN, dt.timeOUT, er.equipmentID "
                + "FROM equipmentreservation er "
                + "JOIN dateandtime dt ON er.datetimeID = dt.dateTimeID "
                + "JOIN equipment e ON er.equipmentID = e.equipmentID "
                + "WHERE dt.date = ? and er.equipmentID = 4 ORDER BY dt.date ASC, dt.timeIN ASC";
        try {
                Connection connection = DriverManager.getConnection(DB_URL, USER, PASS);
                PreparedStatement reservationpst1 = connection.prepareStatement(projectorSQL);
                PreparedStatement reservationpst2 = connection.prepareStatement(screenSQL);
                PreparedStatement reservationpst3 = connection.prepareStatement(speakerSQL);
                PreparedStatement reservationpst4 = connection.prepareStatement(micSQL);
                
                reservationpst1.setString(1, date);
                reservationpst2.setString(1, date);
                reservationpst3.setString(1, date);
                reservationpst4.setString(1, date);
                
                ResultSet rs1 = reservationpst1.executeQuery();
                ResultSet rs2 = reservationpst2.executeQuery();
                ResultSet rs3 = reservationpst3.executeQuery();
                ResultSet rs4 = reservationpst4.executeQuery();
                while (rs1.next()) {
                String date2 = rs1.getString("date");
                String timeIN = rs1.getString("timeIN");
                String timeOUT = rs1.getString("timeOUT");

                model1.addRow(new Object[]{date2, timeIN,timeOUT});
                }
                while (rs2.next()) {
                String date2 = rs2.getString("date");
                String timeIN = rs2.getString("timeIN");
                String timeOUT = rs2.getString("timeOUT");

                model2.addRow(new Object[]{date2, timeIN,timeOUT});
                }
                while (rs3.next()) {
                String date2 = rs3.getString("date");
                String timeIN = rs3.getString("timeIN");
                String timeOUT = rs3.getString("timeOUT");
                model3.addRow(new Object[]{date2, timeIN,timeOUT});
                }
                while (rs4.next()) {
                String date2 = rs4.getString("date");
                String timeIN = rs4.getString("timeIN");
                String timeOUT = rs4.getString("timeOUT");

                model4.addRow(new Object[]{date2, timeIN,timeOUT});
                }
                } catch (SQLException ex) {
                    Logger.getLogger(dashboardFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
                projectorTable.setEnabled(false);
                screenTable.setEnabled(false);
                speakerTable.setEnabled(false);
                micTable.setEnabled(false);
                
                projectorTable.setModel(model1);
                screenTable.setModel(model2);
                speakerTable.setModel(model3);
                micTable.setModel(model4);
    }//GEN-LAST:event_checkButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        //resets table
        apptResHistory.setModel(new DefaultTableModel(null,new Object[]{"id","Date", "Time", "Office"}){public boolean isCellEditable(int rowIndex,int oolumnIndex){return false;}});
        resHistoryTable.setModel(new DefaultTableModel(null,new Object[]{"id","Date", "Time In","Time Out", "Equipment"}){public boolean isCellEditable(int rowIndex,int oolumnIndex){return false;}});
        //hides the id
        TableColumnModel tcm1 = resHistoryTable.getColumnModel();
        tcm1.removeColumn( tcm1.getColumn(0) );
        TableColumnModel tcm2 = apptResHistory.getColumnModel();
        tcm2.removeColumn( tcm2.getColumn(0) );
        //get table
        equip.getReservationHistory(user.getId(),resHistoryTable);
        appoint.getAppointmentHistory(user.getId(),apptResHistory);
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void apptResHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apptResHistoryMouseClicked

    }//GEN-LAST:event_apptResHistoryMouseClicked

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        //delete a row in the table
        int rowIndex1 = resHistoryTable.getSelectedRow();
        int rowIndex2 = apptResHistory.getSelectedRow();

        try {
            if (rowIndex1 != -1) {
                int reservationID = Integer.valueOf(resHistoryTable.getModel().getValueAt(rowIndex1, 0).toString());
                //int equipment = Integer.valueOf(resHistoryTable.getModel().getValueAt(rowIndex1, 4).toString());
                if (equip.removeReservation(reservationID)) {
                    JOptionPane.showMessageDialog(rootPane, "Reservation has been cancelled!", "Cancelled Reservation", JOptionPane.INFORMATION_MESSAGE);
                    resHistoryTable.setModel(new DefaultTableModel(null, new Object[]{"id", "Date", "Time In","Time Out", "Equipment"}){public boolean isCellEditable(int rowIndex,int oolumnIndex){return false;}});
                    TableColumnModel tcm = resHistoryTable.getColumnModel();
                    tcm.removeColumn(tcm.getColumn(0));
                    equip.getReservationHistory(user.getId(), resHistoryTable);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Reservation not cancelled", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else if (rowIndex2 != -1) {
                int appointmentID = Integer.valueOf(apptResHistory.getModel().getValueAt(rowIndex2, 0).toString());
                if (appoint.removeAppointment(appointmentID)) {
                    JOptionPane.showMessageDialog(rootPane, "Appointment has been cancelled!", "Cancelled Appointment", JOptionPane.INFORMATION_MESSAGE);
                    apptResHistory.setModel(new DefaultTableModel(null, new Object[]{"id", "Date", "Time", "Office"}){public boolean isCellEditable(int rowIndex,int oolumnIndex){return false;}});
                    TableColumnModel tcm = apptResHistory.getColumnModel();
                    tcm.removeColumn(tcm.getColumn(0));
                    appoint.getAppointmentHistory(user.getId(), apptResHistory);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Appointment not cancelled", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "No row selected", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(rootPane, "Invalid ID format: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "An error occurred: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void purposeTextAreaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_purposeTextAreaFocusGained
        if (purposeTextArea.getText().equals("Provide a brief description...")){
            purposeTextArea.setText("");
            purposeTextArea.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_purposeTextAreaFocusGained

    private void purposeTextAreaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_purposeTextAreaFocusLost
        if (purposeTextArea.getText().equals("")){
            purposeTextArea.setText("Provide a brief description...");
            purposeTextArea.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_purposeTextAreaFocusLost

    private void refreshButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButton1ActionPerformed
        equip.getAllReservation(projectorTable,screenTable,speakerTable,micTable);
        dateChooser.setCalendar(null);
    }//GEN-LAST:event_refreshButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
        
    
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new Login().setVisible(true);
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apptButton;
    private com.toedter.calendar.JDateChooser apptDateChooser;
    private javax.swing.JPanel apptPanel;
    private javax.swing.JTable apptResHistory;
    private javax.swing.JButton apptSubmitButton;
    private javax.swing.JLabel birthDateLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton checkButton;
    private javax.swing.JTextArea concernTextArea;
    private javax.swing.JLabel contactNumberLabel;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JButton equipButton;
    private javax.swing.JCheckBox equipCheckBox1;
    private javax.swing.JCheckBox equipCheckBox2;
    private javax.swing.JCheckBox equipCheckBox3;
    private javax.swing.JCheckBox equipCheckBox4;
    private javax.swing.JPanel equipPanel;
    private javax.swing.JButton equipSubmitButton;
    private javax.swing.JLabel fnameLabel;
    private javax.swing.JLabel fnameLabel1;
    private javax.swing.JLabel fnameLabel3;
    private javax.swing.JLabel fnameLabel4;
    private javax.swing.JLabel fnameLabel5;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JTable micTable;
    private javax.swing.JComboBox<String> officeComboBox;
    private javax.swing.JPanel parentPanel;
    private javax.swing.JComboBox<String> professorComboBox;
    private javax.swing.JLabel programLabel;
    private javax.swing.JTable projectorTable;
    private javax.swing.JTextArea purposeTextArea;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton refreshButton1;
    private javax.swing.JTable resHistoryTable;
    private javax.swing.JTable screenTable;
    private javax.swing.JTextField searchTextField1;
    private javax.swing.JTable speakerTable;
    private javax.swing.JLabel studNumApptLabel;
    private javax.swing.JLabel studentNumberLabel;
    private javax.swing.JLabel studentNumberLabel1;
    private javax.swing.JLabel studentNumberLabel2;
    private javax.swing.JLabel studentNumberLabel3;
    private javax.swing.JLabel studentNumberLabel4;
    private javax.swing.JLabel studentNumberLabel5;
    private javax.swing.JComboBox<String> timeComboBox;
    private javax.swing.JComboBox<String> timeComboBox1;
    private javax.swing.JComboBox<String> timeComboBox2;
    private javax.swing.JLabel titleBar;
    private javax.swing.JButton userButton;
    private javax.swing.JPanel userPanel;
    private javax.swing.JLabel yearSectionLabel;
    // End of variables declaration//GEN-END:variables
}
